import { ProdutoItem } from "../types";

export const produtosMock: ProdutoItem[] = [
  {
    id: "k-200r",
    image: "/produtos/K-200R®.png",
    model: "K-200R®",
    href: "/produtos/k-200r",
    slug: "k-200r",
    videoPlaybackId: "FcYHH5Z6FiXTkhO2DHNZuTrVTTDjk5KQ9SC8ChvhOJ8",
    i18n: {
      "pt-BR": {
        title: "Porta Automática Deslizante",
        description: "Porta Automática Automec modelo K-200R, aplicada em 1 ou 2 folhas móveis de vidro ou caixilho em alumínio AT-45, com capacidade de até 250kg. Deslizamento sobre roldanas injetadas em nylon. Tração por correia dentada de neoprene, revestida de nylon e alma de fibra de vidro. Trilho superior, trilho interno removível, tampa superior e tampa frontal em alumínio liga 6063 T6.\n\nAcabamento em Pintura Eletrostática ou Inox. Unidade de comando micro processada STM com ajuste de velocidade de abertura, velocidade de fechamento, abertura parcial, torque do motor e temporizador de fechamento. Motor DC 24vcc. Alimentação de entrada para o equipamento 220vca, 60hz, 2,5A, alimentação para os acessórios 24vcc 2,5A. Baterias 24v.",
        idealFor: ["Aeroportos", "Residências", "Hospitais", "Indústrias", "Shoppings", "Hotéis", "Bancos", "Centros Comerciais", "Supermercados"],
        applications: [{ label: "Aplicação em portas de uma folha: 120kg" }, { label: "Aplicação em portas de duas folhas: 200kg" }],
        relatedCategoryLabel: "Portas automáticas",
        catalog: [
          { title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Baixar Catálogo", href: "#", icon: "download" }] },
          { title: "DWG – Desenho Técnico", image: "/produtos/dwg.png", actions: [{ label: "Visualizar", href: "#", icon: "view" }, { label: "Baixar .zip", href: "#", icon: "download" }] },
          { title: "Simulador 360°", image: "/produtos/simulador.png", actions: [{ label: "Acessar", href: "#", icon: "external" }] },
        ],
        technicalSpecs: [
          { tabLabel: "Modelo K-200®", specs: [
            { label: "Fluxo", value: "Table Contínuo – Alto / 2.000.000 de ciclos" },
            { label: "Peso máximo", value: "150 kg (1 folha) / 250 kg (2 folhas)" },
            { label: "Deslizamento", value: "Roldanas injetadas em Nylon" },
            { label: "Tração", value: "Correia dentada de neoprene, revestida de nylon e alma de fibra de vidro" },
            { label: "Medidas do trilho em alumínio", value: "152mm (L) x 85mm (H)" },
            { label: "Medidas da tampa em alumínio", value: "87mm (L) x 117mm (H)" },
            { label: "Comprimento máximo do trilho", value: "6600mm" },
            { label: "Motor", value: "DC 24vcc 85 W / Brushless" },
            { label: "Unidade de comando", value: "Central microprocessada STM" },
            { label: "Velocidade máxima de abertura", value: "0,5 m/s (1 folha) / 0,7 m/s (2 folhas)" },
            { label: "Velocidade máxima ao fechar", value: "0,5 m/s (1 folha) / 0,7 m/s (2 folhas)" },
            { label: "Alimentação – Automatizador", value: "220vca / 50-60hz / 2,5A" },
            { label: "Alimentação – Acessórios", value: "24vcc / 2,5A" },
            { label: "Funções reguláveis", value: "Temporizador de fechamento, abertura parcial, velocidade de abertura, velocidade de fechamento e torque do motor." },
            { label: "Funcionamento de emergência", value: "Sistema de série padrão – Para manter a porta aberta em caso de falta de energia" },
          ]},
          { tabLabel: "Desenho Técnico", specs: [] },
        ],
      },
      en: {
        title: "Sliding Automatic Door",
        description: "Automec automatic door model K-200R, applied in 1 or 2 movable glass leaves or aluminum frame AT-45, with capacity up to 250kg. Sliding on nylon injected rollers. Timing belt drive made of neoprene, coated with nylon and fiberglass core. Top rail, removable internal rail, top cover and front cover in 6063 T6 aluminum alloy.\n\nElectrostatic Painting or Stainless Steel finish. STM microprocessed control unit with opening speed, closing speed, partial opening, motor torque and closing timer adjustment. DC 24vcc motor. Input power 220vac, 60hz, 2.5A, accessory power 24vcc 2.5A. 24v batteries.",
        idealFor: ["Airports", "Residences", "Hospitals", "Industries", "Shopping Malls", "Hotels", "Banks", "Commercial Centers", "Supermarkets"],
        applications: [{ label: "Single leaf door application: 120kg" }, { label: "Double leaf door application: 200kg" }],
        relatedCategoryLabel: "Automatic doors",
        catalog: [
          { title: "Technical Catalog", image: "/produtos/catalogo.png", actions: [{ label: "Download Catalog", href: "#", icon: "download" }] },
          { title: "DWG – Technical Drawing", image: "/produtos/dwg.png", actions: [{ label: "View", href: "#", icon: "view" }, { label: "Download .zip", href: "#", icon: "download" }] },
          { title: "360° Simulator", image: "/produtos/simulador.png", actions: [{ label: "Access", href: "#", icon: "external" }] },
        ],
        technicalSpecs: [
          { tabLabel: "Model K-200®", specs: [
            { label: "Operation mode", value: "Sliding / Telescopic / STS-20 Panic" },
            { label: "Flow", value: "Continuous Table – High / 2,000,000 cycles" },
            { label: "Max weight", value: "150 kg (1 leaf) / 250 kg (2 leaves)" },
            { label: "Sliding", value: "Nylon injected rollers" },
            { label: "Drive", value: "Neoprene timing belt, nylon coated and fiberglass core" },
            { label: "Aluminum rail dimensions", value: "152mm (W) x 85mm (H)" },
            { label: "Aluminum cover dimensions", value: "87mm (W) x 117mm (H)" },
            { label: "Max rail length", value: "6600mm" },
            { label: "Motor", value: "DC 24vcc 85 W / Brushless" },
            { label: "Control unit", value: "STM microprocessed central" },
            { label: "Max opening speed", value: "0.5 m/s (1 leaf) / 0.7 m/s (2 leaves)" },
            { label: "Max closing speed", value: "0.5 m/s (1 leaf) / 0.7 m/s (2 leaves)" },
            { label: "Power – Operator", value: "220vac / 50-60hz / 2.5A" },
            { label: "Power – Accessories", value: "24vcc / 2.5A" },
            { label: "Adjustable functions", value: "Closing timer, partial opening, opening speed, closing speed and motor torque." },
            { label: "Emergency operation", value: "Standard series system – To keep the door open in case of power failure" },
          ]},
          { tabLabel: "Technical Drawing", specs: [] },
        ],
      },
      es: {
        title: "Puerta Automática Deslizante",
        description: "Puerta Automática Automec modelo K-200R, aplicada en 1 o 2 hojas móveis de vidro o marco de aluminio AT-45, con capacidad de hasta 250kg. Deslizamiento sobre rodillos inyectados en nylon. Tracción por correa dentada de neopreno, recubierta de nylon y alma de fibra de vidrio. Riel superior, riel interno extraíble, tapa superior y tapa frontal en aleación de aluminio 6063 T6.\n\nAcabado en Pintura Electrostática o Acero Inoxidable. Unidad de control microprocesada STM con ajuste de velocidad de apertura, velocidad de cierre, apertura parcial, torque del motor y temporizador de cierre. Motor DC 24vcc. Alimentación de entrada 220vca, 60hz, 2,5A, alimentación para accesorios 24vcc 2,5A. Baterías 24v.",
        idealFor: ["Aeropuertos", "Residencias", "Hospitales", "Industrias", "Centros Comerciales", "Hoteles", "Bancos", "Centros Comerciales", "Supermercados"],
        applications: [{ label: "Aplicación en puertas de una hoja: 120kg" }, { label: "Aplicación en puertas de dos hojas: 200kg" }],
        relatedCategoryLabel: "Puertas automáticas",
        catalog: [
          { title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Descargar Catálogo", href: "#", icon: "download" }] },
          { title: "DWG – Dibujo Técnico", image: "/produtos/dwg.png", actions: [{ label: "Visualizar", href: "#", icon: "view" }, { label: "Descargar .zip", href: "#", icon: "download" }] },
          { title: "Simulador 360°", image: "/produtos/simulador.png", actions: [{ label: "Acceder", href: "#", icon: "external" }] },
        ],
        technicalSpecs: [
          { tabLabel: "Modelo K-200®", specs: [
            { label: "Modo de funcionamiento", value: "Deslizante / Telescópica / STS-20 Antipánico" },
            { label: "Flujo", value: "Mesa Continua – Alto / 2.000.000 de ciclos" },
            { label: "Peso máximo", value: "150 kg (1 hoja) / 250 kg (2 hojas)" },
            { label: "Deslizamiento", value: "Rodillos inyectados en Nylon" },
            { label: "Tracción", value: "Correa dentada de neopreno, recubierta de nylon y alma de fibra de vidrio" },
            { label: "Dimensiones del riel de aluminio", value: "152mm (A) x 85mm (H)" },
            { label: "Dimensiones de la tapa de aluminio", value: "87mm (A) x 117mm (H)" },
            { label: "Longitud máxima del riel", value: "6600mm" },
            { label: "Motor", value: "DC 24vcc 85 W / Brushless" },
            { label: "Unidad de control", value: "Central microprocesada STM" },
            { label: "Velocidad máxima de apertura", value: "0,5 m/s (1 hoja) / 0,7 m/s (2 hojas)" },
            { label: "Velocidad máxima al cerrar", value: "0,5 m/s (1 hoja) / 0,7 m/s (2 hojas)" },
            { label: "Alimentación – Automatizador", value: "220vca / 50-60hz / 2,5A" },
            { label: "Alimentación – Accesorios", value: "24vcc / 2,5A" },
            { label: "Funciones ajustables", value: "Temporizador de cierre, apertura parcial, velocidad de apertura, velocidad de cierre y torque del motor." },
            { label: "Funcionamiento de emergencia", value: "Sistema de serie estándar – Para mantener a porta aberta em caso de falta de energia" },
          ]},
          { tabLabel: "Dibujo Técnico", specs: [] },
        ],
      },
    },
    applications: [
      { image: "/produtos/aplicacao-1folha.png" },
      { image: "/produtos/aplicacao-2folhas.png" },
    ],
    relatedCategoryHref: "#",
  },
  {
    id: "k-500r",
    image: "/produtos/K-500R®.png",
    model: "K-500R®",
    href: "/produtos/k-500r",
    slug: "k-500r",
    videoPlaybackId: "Se57ug001px3tdXw00quRrSUi004FYqlK1QoxD1Vks3lrI",
    i18n: {
      "pt-BR": {
        title: "Porta Automática Deslizante",
        description: "Porta Automática Automec modelo K-500R, projetada para aplicações de alto tráfego com folhas de vidro de grande porte. Capacidade de até 500kg em configuração telescópica. Sistema de tração por correia dentada com motor brushless de alta performance.",
        idealFor: ["Aeroportos", "Hospitais", "Shoppings", "Centros Comerciais", "Hotéis", "Indústrias"],
        applications: [{ label: "Aplicação em portas de uma folha" }, { label: "Aplicação em portas de duas folhas" }],
        relatedCategoryLabel: "Portas automáticas",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Baixar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo K-500®", specs: [
          { label: "Modo de funcionamento", value: "Deslizante / Telescópica" },
          { label: "Peso máximo", value: "500 kg" },
          { label: "Deslizamento", value: "Roldanas injetadas em Nylon" },
          { label: "Tração", value: "Correia dentada de neoprene" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidade de comando", value: "Central microprocessada STM" },
          { label: "Alimentação – Automatizador", value: "220vca / 50-60hz" },
        ]}],
      },
      en: {
        title: "Sliding Automatic Door",
        description: "Automec automatic door model K-500R, designed for high-traffic applications with large glass leaves. Capacity up to 500kg in telescopic configuration. Timing belt drive system with high-performance brushless motor.",
        idealFor: ["Airports", "Hospitals", "Shopping Malls", "Commercial Centers", "Hotels", "Industries"],
        applications: [{ label: "Single leaf door application" }, { label: "Double leaf door application" }],
        relatedCategoryLabel: "Automatic doors",
        catalog: [{ title: "Technical Catalog", image: "/produtos/catalogo.png", actions: [{ label: "Download Catalog", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Model K-500®", specs: [
          { label: "Operation mode", value: "Sliding / Telescopic" },
          { label: "Max weight", value: "500 kg" },
          { label: "Sliding", value: "Nylon injected rollers" },
          { label: "Drive", value: "Neoprene timing belt" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Control unit", value: "STM microprocessed central" },
          { label: "Power – Operator", value: "220vac / 50-60hz" },
        ]}],
      },
      es: {
        title: "Puerta Automática Deslizante",
        description: "Puerta Automática Automec modelo K-500R, diseñada para aplicaciones de alto tráfico con hojas de vidro de gran tamaño. Capacidad de hasta 500kg en configuración telescópica. Sistema de tracción por correa dentada con motor brushless de alto rendimiento.",
        idealFor: ["Aeropuertos", "Hospitales", "Centros Comerciales", "Centros Comerciales", "Hoteles", "Industrias"],
        applications: [{ label: "Aplicación en puertas de una hoja" }, { label: "Aplicación en puertas de dos hojas" }],
        relatedCategoryLabel: "Puertas automáticas",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Descargar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo K-500®", specs: [
          { label: "Modo de funcionamiento", value: "Deslizante / Telescópica" },
          { label: "Peso máximo", value: "500 kg" },
          { label: "Deslizamiento", value: "Rodillos inyectados en Nylon" },
          { label: "Tracción", value: "Correa dentada de neopreno" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidad de control", value: "Central microprocesada STM" },
          { label: "Alimentación – Automatizador", value: "220vca / 50-60hz" },
        ]}],
      },
    },
    applications: [{ image: "/produtos/aplicacao-1folha.png" }, { image: "/produtos/aplicacao-2folhas.png" }],
    relatedCategoryHref: "#",
  },
  {
    id: "sts-20",
    image: "/produtos/STS-20®.png",
    model: "STS-20®",
    href: "/produtos/sts-20",
    slug: "sts-20",
    videoPlaybackId: "01qnSkueaczskw66X7G4lgE9I5dIdlz018kGorkfVDpbk",
    i18n: {
      "pt-BR": {
        title: "Porta Automática Antipânico",
        description: "Sistema antipânico Automec modelo STS-20, projetado para garantir a segurança e evacuação de emergência. Ativação automática em caso de incêndio, abrindo as portas para facilitar a saída de pessoas. Conforme normas ABNT NBR 15202, NBR 16025 e NBR 9077.",
        idealFor: ["Hospitais", "Indústrias", "Shoppings", "Centros Comerciais", "Bancos", "Hotéis"],
        applications: [{ label: "Aplicação em portas de uma folha" }],
        relatedCategoryLabel: "Portas antipânico",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Baixar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo STS-20®", specs: [
          { label: "Modo de funcionamento", value: "Antipânico" },
          { label: "Normas", value: "ABNT NBR 15202, NBR 16025, NBR 9077" },
          { label: "Peso máximo", value: "200 kg" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidade de comando", value: "Central microprocessada STM" },
        ]}],
      },
      en: {
        title: "Panic Automatic Door",
        description: "Automec panic system model STS-20, designed to ensure safety and emergency evacuation. Automatic activation in case of fire, opening doors to facilitate people exit. Compliant with ABNT standards NBR 15202, NBR 16025 and NBR 9077.",
        idealFor: ["Hospitals", "Industries", "Shopping Malls", "Commercial Centers", "Banks", "Hotels"],
        applications: [{ label: "Single leaf door application" }],
        relatedCategoryLabel: "Panic doors",
        catalog: [{ title: "Technical Catalog", image: "/produtos/catalogo.png", actions: [{ label: "Download Catalog", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Model STS-20®", specs: [
          { label: "Operation mode", value: "Panic" },
          { label: "Standards", value: "ABNT NBR 15202, NBR 16025, NBR 9077" },
          { label: "Max weight", value: "200 kg" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Control unit", value: "STM microprocessed central" },
        ]}],
      },
      es: {
        title: "Puerta Automática Antipánico",
        description: "Sistema antipánico Automec modelo STS-20, diseñado para garantizar la seguridad y evacuación de emergencia. Activación automática en caso de incendio, abriendo las portas para facilitar la salida de personas. Conforme a normas ABNT NBR 15202, NBR 16025 y NBR 9077.",
        idealFor: ["Hospitales", "Industrias", "Centros Comerciales", "Centros Comerciales", "Bancos", "Hoteles"],
        applications: [{ label: "Aplicación en puertas de una hoja" }],
        relatedCategoryLabel: "Puertas antipánico",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Descargar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo STS-20®", specs: [
          { label: "Modo de funcionamiento", value: "Antipánico" },
          { label: "Normas", value: "ABNT NBR 15202, NBR 16025, NBR 9077" },
          { label: "Peso máximo", value: "200 kg" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidad de control", value: "Central microprocesada STM" },
        ]}],
      },
    },
    applications: [{ image: "/produtos/aplicacao-1folha.png" }],
    relatedCategoryHref: "#",
  },
  {
    id: "sth-70",
    image: "/produtos/STH-70®.png",
    model: "STH-70®",
    href: "/produtos/sth-70",
    slug: "sth-70",
    videoPlaybackId: "GhnI63p56YkTqPM7C8AZ7Z481qQn6eu98M5SThYiZ5Y",
    i18n: {
      "pt-BR": {
        title: "Porta Automática para Ambientes Controlados",
        description: "Porta Automática Automec modelo STH-70, ideal para ambientes controlados como câmaras frias, laboratórios e salas limpas. Sistema hermético com vedação completa para manter a integridade do ambiente interno.",
        idealFor: ["Laboratórios", "Hospitais", "Indústrias", "Câmaras Frias", "Salas Limpas", "Farmacêuticas"],
        applications: [{ label: "Aplicação em ambientes controlados" }],
        relatedCategoryLabel: "Portas ambientes controlados",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Baixar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo STH-70®", specs: [
          { label: "Modo de funcionamento", value: "Hermetic / Ambientes Controlados" },
          { label: "Peso máximo", value: "300 kg" },
          { label: "Vedação", value: "Hermética com selo de borracha" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidade de comando", value: "Central microprocessada STM" },
        ]}],
      },
      en: {
        title: "Automatic Door for Controlled Environments",
        description: "Automec automatic door model STH-70, ideal for controlled environments such as cold rooms, laboratories and clean rooms. Hermetic system with complete sealing to maintain the integrity of the internal environment.",
        idealFor: ["Laboratories", "Hospitals", "Industries", "Cold Rooms", "Clean Rooms", "Pharmaceutical"],
        applications: [{ label: "Controlled environment application" }],
        relatedCategoryLabel: "Controlled environment doors",
        catalog: [{ title: "Technical Catalog", image: "/produtos/catalogo.png", actions: [{ label: "Download Catalog", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Model STH-70®", specs: [
          { label: "Operation mode", value: "Hermetic / Controlled Environment" },
          { label: "Max weight", value: "300 kg" },
          { label: "Sealing", value: "Hermetic with rubber seal" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Control unit", value: "STM microprocessed central" },
        ]}],
      },
      es: {
        title: "Puerta Automática para Ambientes Controlados",
        description: "Puerta Automática Automec modelo STH-70, ideal para ambientes controlados como cámaras frías, laboratorios y salas limpias. Sistema hermético con sellado completo para mantener la integridad del ambiente interno.",
        idealFor: ["Laboratorios", "Hospitales", "Industrias", "Cámaras Frías", "Salas Limpias", "Farmacéuticas"],
        applications: [{ label: "Aplicación en ambientes controlados" }],
        relatedCategoryLabel: "Puertas ambientes controlados",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Descargar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo STH-70®", specs: [
          { label: "Modo de funcionamiento", value: "Hermetic / Ambientes Controlados" },
          { label: "Peso máximo", value: "300 kg" },
          { label: "Sellado", value: "Hermético con sello de goma" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidad de control", value: "Central microprocesada STM" },
        ]}],
      },
    },
    applications: [{ image: "/produtos/aplicacao-1folha.png" }],
    relatedCategoryHref: "#",
  },
  {
    id: "stc-40",
    image: "/produtos/STC-40®.png",
    model: "STC-40®",
    href: "/produtos/stc-40",
    slug: "stc-40",
    videoPlaybackId: "zLtdeJhJfo4CUzEAkSanu01jeLdVYcwG0181pOB2m02x2w",
    i18n: {
      "pt-BR": {
        title: "Porta Automática Telescópica",
        description: "Porta Automática Automec modelo STC-40, sistema telescópico que permite a abertura de folhas móveis em dimensões reduzidas. Ideal para corredores estreitos e ambientes com espaço limitado de abertura.",
        idealFor: ["Hotéis", "Hospitais", "Residências", "Shoppings", "Centros Comerciais"],
        applications: [{ label: "Aplicação telescópica em corredores" }],
        relatedCategoryLabel: "Portas telescópicas",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Baixar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo STC-40®", specs: [
          { label: "Modo de funcionamento", value: "Telescópica" },
          { label: "Peso máximo", value: "200 kg" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidade de comando", value: "Central microprocessada STM" },
        ]}],
      },
      en: {
        title: "Telescopic Automatic Door",
        description: "Automec automatic door model STC-40, telescopic system that allows opening of movable leaves in reduced dimensions. Ideal for narrow corridors and environments with limited opening space.",
        idealFor: ["Hotels", "Hospitals", "Residences", "Shopping Malls", "Commercial Centers"],
        applications: [{ label: "Telescopic application in corridors" }],
        relatedCategoryLabel: "Telescopic doors",
        catalog: [{ title: "Technical Catalog", image: "/produtos/catalogo.png", actions: [{ label: "Download Catalog", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Model STC-40®", specs: [
          { label: "Operation mode", value: "Telescopic" },
          { label: "Max weight", value: "200 kg" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Control unit", value: "STM microprocessed central" },
        ]}],
      },
      es: {
        title: "Puerta Automática Telescópica",
        description: "Puerta Automática Automec modelo STC-40, sistema telescópico que permite la apertura de hojas móveis en dimensiones reduzidas. Ideal para pasillos estrechos y ambientes con espacio limitado de apertura.",
        idealFor: ["Hoteles", "Hospitales", "Residencias", "Centros Comerciales", "Centros Comerciales"],
        applications: [{ label: "Aplicación telescópica en pasillos" }],
        relatedCategoryLabel: "Puertas telescópicas",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Descargar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelo STC-40®", specs: [
          { label: "Modo de funcionamiento", value: "Telescópica" },
          { label: "Peso máximo", value: "200 kg" },
          { label: "Motor", value: "DC 24vcc Brushless" },
          { label: "Unidad de control", value: "Central microprocesada STM" },
        ]}],
      },
    },
    applications: [{ image: "/produtos/aplicacao-2folhas.png" }],
    relatedCategoryHref: "#",
  },
  {
    id: "b120-b300",
    image: "/produtos/B-120T®  B-300T®.png",
    model: "B-120T® / B-300T®",
    href: "/produtos/b-120t-b-300t",
    slug: "b-120t-b-300t",
    videoPlaybackId: "lDmfWAGTp012uP5gENhUMklmFaRKCQPuH02V9ZRa4O2w8",
    i18n: {
      "pt-BR": {
        title: "Porta Automática de Batente",
        description: "Porta Automática Automec modelos B-120T e B-300T, soluções compactas para portas de vidro com menor peso. Sistema de tração por correia dentada com motor de alta durabilidade. Ideal para entradas comerciais e residenciais.",
        idealFor: ["Residências", "Lojas", "Escritórios", "Clínicas", "Farmácias", "Supermercados"],
        applications: [{ label: "Aplicação em portas de uma folha" }],
        relatedCategoryLabel: "Portas automáticas",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Baixar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelos B-120T / B-300T", specs: [
          { label: "Modo de funcionamento", value: "Deslizante" },
          { label: "Peso máximo", value: "120 kg (B-120T) / 300 kg (B-300T)" },
          { label: "Deslizamento", value: "Roldanas injetadas em Nylon" },
          { label: "Tração", value: "Correia dentada de neoprene" },
          { label: "Motor", value: "DC 24vcc" },
          { label: "Unidade de comando", value: "Central microprocessada" },
        ]}],
      },
      en: {
        title: "Swing Automatic Door",
        description: "Automec automatic door models B-120T and B-300T, compact solutions for lighter glass doors. Timing belt drive system with high-durability motor. Ideal for commercial and residential entrances.",
        idealFor: ["Residences", "Stores", "Offices", "Clinics", "Pharmacies", "Supermarkets"],
        applications: [{ label: "Single leaf door application" }],
        relatedCategoryLabel: "Automatic doors",
        catalog: [{ title: "Technical Catalog", image: "/produtos/catalogo.png", actions: [{ label: "Download Catalog", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Models B-120T / B-300T", specs: [
          { label: "Operation mode", value: "Sliding" },
          { label: "Max weight", value: "120 kg (B-120T) / 300 kg (B-300T)" },
          { label: "Sliding", value: "Nylon injected rollers" },
          { label: "Drive", value: "Neoprene timing belt" },
          { label: "Motor", value: "DC 24vcc" },
          { label: "Control unit", value: "Microprocessed central" },
        ]}],
      },
      es: {
        title: "Puerta Automática Batiente",
        description: "Puertas Automáticas Automec modelos B-120T y B-300T, soluciones compactas para puertas de vidro con menor peso. Sistema de tracción por correa dentada con motor de alta durabilidad. Ideal para entradas comerciales y residenciales.",
        idealFor: ["Residencias", "Tiendas", "Oficinas", "Clínicas", "Farmacias", "Supermercados"],
        applications: [{ label: "Aplicación en puertas de una hoja" }],
        relatedCategoryLabel: "Puertas automáticas",
        catalog: [{ title: "Catálogo Técnico", image: "/produtos/catalogo.png", actions: [{ label: "Descargar Catálogo", href: "#", icon: "download" }] }],
        technicalSpecs: [{ tabLabel: "Modelos B-120T / B-300T", specs: [
          { label: "Modo de funcionamiento", value: "Deslizante" },
          { label: "Peso máximo", value: "120 kg (B-120T) / 300 kg (B-300T)" },
          { label: "Deslizamiento", value: "Rodillos inyectados en Nylon" },
          { label: "Tracción", value: "Correa dentada de neopreno" },
          { label: "Motor", value: "DC 24vcc" },
          { label: "Unidad de control", value: "Central microprocesada" },
        ]}],
      },
    },
    applications: [{ image: "/produtos/aplicacao-1folha.png" }],
    relatedCategoryHref: "#",
  },
];

export const getProdutos = async (): Promise<ProdutoItem[]> => {
  return new Promise((resolve) => {
    setTimeout(() => resolve(produtosMock), 100);
  });
};

export const getProdutoBySlug = async (slug: string): Promise<ProdutoItem | undefined> => {
  return new Promise((resolve) => {
    setTimeout(() => resolve(produtosMock.find((p) => p.slug === slug)), 100);
  });
};
